services:
  mysql:
    image: mysql:latest
    container_name: axzy-berlin89-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root12345
      - MYSQL_DATABASE=axzy_berlin89
      - MYSQL_USER=berlin89
      - MYSQL_PASSWORD=berlin8912345
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data:
