-- AlterTable
ALTER TABLE `BoxCut` MODIFY `card` INTEGER NOT NULL DEFAULT 0,
    MODIFY `btc` INTEGER NOT NULL DEFAULT 0,
    MODIFY `cash` INTEGER NOT NULL DEFAULT 0,
    MODIFY `cashUSD` INTEGER NOT NULL DEFAULT 0,
    MODIFY `image` VARCHAR(191) NOT NULL DEFAULT '';
